### ISSUE TITLE
-> epinowcast.org

### ISSUE THREAD

**Issue by seabbs** [epinowcast/hashprng#10]
Is this in scope and do you/we want to move it into the organisation?

**Comment by pearsonca** [comment]
Feels like "in scope" is a *you* question?

I'm not fussed either way, but matched scenario analysis doesn't strike me as "nowcast" topic. Definitely an "epi" and modelling/analysis Q, but very much in the traditional vein of assuming-we-know-X, what does changing Y accomplish?

Or are you viewing epinowcast as covering a broader topic area?

**Comment by seabbs** [comment]
> We are a community of infectious disease modellers, applied epidemiologists, software developers, and others building a suite of tools for real-time analysis of infectious diseases. On top of developing these tools, we also do research on when they work and when they don’t, write case studies to showcase best practices, support users and decision-makers, and compare our work to that of others.

(from the site for ref).

I think its in scope but its not meant to be a me question its meant to be member driven. 

> aside: most of the infrastructure additions are ported from epinowcast, feature all those urls, and so on - if we don't go under epinowcast, rough estimate on the added work to set up e.g package down hosting?

It is all pretty easy but you will need to do it as it is your pages sight etc.

**Comment by pearsonca** [comment]
Righto, have teed it up for people to opine on: https://community.epinowcast.org/t/stochastic-scenario-analysis-tool/181

**Comment by seabbs** [comment]
So you should be able to do the move (if we are going ahead with it) in the settings.

**Comment by pearsonca** [comment]
addressed in 5ca66680fdf38431318f42504eaa0763e11bda86
