### ISSUE TITLE
Rename default branch -> `main`

### ISSUE THREAD

**Issue by seabbs** [epinowcast/hashprng#9]
See the `usethis` vignette for this. I don't have permissions to do this.

**Comment by pearsonca** [comment]
`usethis` doesn't seem to have a vignette - what specifically are you referencing here?

**Comment by seabbs** [comment]
See here: https://www.tidyverse.org/blog/2021/10/renaming-default-branch/

**Comment by pearsonca** [comment]
ah, i know _how_ to take care of this. was looking more for the "why bother" - case seems to be "its the trend." :shrug: fine by me, i suppose.

**Comment by seabbs** [comment]
`master` is not positive language

**Comment by seabbs** [comment]
Also see here: https://sfconservancy.org/news/2020/jun/23/gitbranchname/

**Comment by pearsonca** [comment]
don't agree with that assertion, but also not fussed re the change.

**Comment by seabbs** [comment]
> don't agree with that assertion, but also not fussed re the change.

Which assertion? I think using community standards is a good idea regardless?

**Comment by pearsonca** [comment]
Re master not positive, and that it shouldn't be normalized. Agree that stating & enforcing community standards is useful - and I don't have to agree with all the standards and/or their motivation to abide by them.

**Comment by seabbs** [comment]
You need to make this change @pearsonca ...

```r
git_default_branch_rename(to = "main")
✔ Setting active project to '/home/seabbs/Dropbox/academic/projects/hbmPRNG'
Error: You don't seem to have admin permissions for the source repo 'pearsonca/hbmPRNG', which is required to rename the default branch.
```

**Comment by pearsonca** [comment]
@seabbs did the epinowcast move in the wrong order here - should have dressed this first. guess you have it now?

**Comment by seabbs** [comment]
Done. Note @pearsonca you are now an admin as I think that was blocking this before.
